sudo mkdir -p /data/conf
sudo mkdir -p /data/mongos/log
sudo mkdir -p /data/config/data
sudo mkdir -p /data/config/log
sudo mkdir -p /data/shard1/data
sudo mkdir -p /data/shard1/log
sudo mkdir -p /data/shard2/data
sudo mkdir -p /data/shard2/log
sudo mkdir -p /data/shard3/data
sudo mkdir -p /data/shard3/log