testCRF: testCRF.cpp crf.cpp
	g++ testCRF.cpp -o ./bin/testCRF -std=c++11 -lpthread -g
testCRFMulThread: testCRFMulThread.cpp crfMulThread.cpp
	g++ testCRFMulThread.cpp -o ./bin/testCRFMulThread -std=c++11 -lpthread -g
